import Head from 'next/head'
import Image from 'next/image'
import SiteIntro from '../components/SiteIntro'

export default function WorkPage() {
  return (
    <>
      <Head>
        <title>johnfry.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SiteIntro />
      <main className='site-main grid'>
        <h1 className='page-title'>
          work
        </h1>
        <div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, alias. Commodi, recusandae sit! Fugit accusamus non blanditiis molestias, possimus at doloremque pariatur neque hic quas quo corrupti nobis tempore labore necessitatibus sit quasi, amet maiores, vel reiciendis dolor qui perferendis provident suscipit! At minima consequatur tenetur sint neque excepturi voluptatem laudantium! Necessitatibus perspiciatis libero, quisquam vitae rerum quasi eius iste doloribus aliquam qui, possimus dolores deleniti corporis numquam laboriosam harum voluptas hic, quibusdam repellat! Qui, nemo necessitatibus est error blanditiis tempore? Expedita, dolores perspiciatis pariatur corporis sapiente iusto impedit odit laudantium necessitatibus tempora? Esse quibusdam odio architecto corporis placeat qui quae sequi voluptates, at, molestiae impedit porro illo cum enim blanditiis sed labore maiores laudantium voluptatem quos. Ratione consequatur qui, at fuga possimus nihil est quidem, officiis dolorem ipsa harum unde placeat necessitatibus debitis dolore voluptas in laborum cupiditate neque repudiandae? Eius aliquid, saepe quod culpa quia neque cumque nihil debitis quos, veniam odio et cum fugiat officia dolore! Provident, similique cupiditate. Nulla doloribus a, placeat voluptatum reiciendis quasi architecto ducimus tempore blanditiis tempora consequatur totam, pariatur provident impedit consequuntur ullam necessitatibus. Amet necessitatibus rerum autem inventore ut dolor, corporis possimus dignissimos eligendi alias quod eius veritatis consequuntur perferendis voluptates?</p>
        </div>
      </main>
    </>
  )
}
